### PR TITLE
Update metacoq

### PR DESCRIPTION
**Pull request by mattam82**
This updates certicoq to the lastest metacoq 8.11 version. The main change is that kernel names are now better reflected as structured names starting with a module path and ending with an ident, avoiding fiddling with "." in CertiCoq in most places. The added benefit of the change is that kernames are now treated mostly as an abstract type with an equality test in all the code and proofs, which should allow easily moving to a different representation, e.g. more space-efficient numbers, if we desire.

### CODE REVIEW

**Comment by mattam82** [comment]
It has been tested here: https://travis-ci.com/github/mattam82/certicoq/builds/172823471
This requires updating and rebuilding submodules, as usual

**Comment by joom** [comment]
If you change https://github.com/PrincetonUniversity/certicoq/blob/7e4b58aacbd890c3057db701931ecf82d1c3f51a/theories/Glue/glue.v#L1405 to 
```coq
  let '(err, st) := runState (make_glue_program (rev globs)) opts init in
```
then the problem with the order to generated glue function in C should be solved.
I can't change and commit because the PR is from your personal fork.

**Comment by mattam82** [comment]
Thanks @joom, I'll fix it!

**Comment by mattam82** [comment]
Indeed, I could test vs_easy as well this way, this all seems to be working well.

**Pull request merged**
