### PR TITLE
Port to Coq 8.12

### PR DESCRIPTION
**Pull request by yforster**
This PR subsumes Matthieu's PR #18.

The respective necessary submodules (which are not correctly set yet because there are open PRs) are:

- `metacoq`: https://github.com/yforster/template-coq/tree/coq-8.12-updates open PR: https://github.com/MetaCoq/metacoq/pull/451
- `coq-ext-lib`: https://github.com/yforster/coq-ext-lib/tree/coq-8.12, open PR: https://github.com/mattam82/coq-ext-lib/pull/1
- `paramcoq`: https://github.com/coq-community/paramcoq/tree/v8.12
- `SquiggleEq`: https://github.com/yforster/SquiggleEq/tree/coq-8.12 open PR: https://github.com/aa755/SquiggleEq/pull/8
- `Equations`: The `coq-equations.1.2.3+8.12` opam package, or https://github.com/mattam82/Coq-Equations/releases/tag/v1.2.3-8.12

Problems:

- One frequent problem when porting code to 8.12 is that `firstorder` used to be `firstorder auto with *`, but now is defined as `firstorder auto with core`. The quick fix (which is not ideal) is to just replace `firstorder` by its old definition at points where proofs break.
- I had to `Import ListNotations` at some points, which shouldn't be a problem.
- The `disjoint_reasoningv2` tactic is broken and sometimes doesn't resolve goals. I have inserted admits at some points because I don't know about the internals of the tactics. Maybe somebody who knows more can have a quick look? The introduced admits in the diff should lead to the relevant points.
- A bit irritatingly, `setoid_rewrite` sometimes didn't work as expected and failed with universe conflicts. Sometimes `setoid_rewrite lem in H` had to be replaced by `revert H; rewrite lem; intros H`, sometimes I applied `proper` lemmas explicitly. One example is `eapply properDisjoint.` in `L4_5_to_L5.v`. @mattam82, maybe you can have a look?

### CODE REVIEW

**Comment by mattam82** [comment]
I can have a look at the setoid_rewrite issue probably only by the end of august. It sounds like a regression though.

**Comment by yforster** [comment]
@mattam82 I pushed the current state. `.v` compilation works fine, but `.ml` compilation fails with
```
Dynlink error: error loading shared library: Dynlink.Error (Dynlink.Cannot_open_dll "Failure(\"/home/yannick/research/certicoq/plugin/certicoq_plugin.cmxs: undefined symbol: camlAST__const_block_25\")")
```
for me. Could you have a look?

I was compiling on top of https://github.com/MetaCoq/metacoq/pull/482 but I think the problem should also appear under any MetaCoq 8.12 version

**Comment by yforster** [comment]
The `metacoq` submodule is still wrong (awaiting merge of [this](https://github.com/MetaCoq/metacoq/pull/494) PR).

Apart from that, everything (including the `.ml` files) now compiles under Coq 8.12.

Maybe the most relevant change is that we do not `open Metacoq_template_plugin` anymore in the Makefile, to work around a bug in `ocamllibdep`. And the most time-consuming problem was that `quote_term_rec` now has to be called with `bypass_opacity` set explicitly to `true`, otherwise compilation errors occur in the vs benchmarks.

For `certicoq_benchmarks.v`, I get for `Time CertiCoq Compile -time -direct main_h.`

```Debug: Time elapsed in Lbox:  1.637266
Debug: Time elapsed in L1g:  0.027236
Debug: Time elapsed in L2k:  0.000839
Debug: Time elapsed in L2k_eta:  0.001261
Debug: Time elapsed in L4:  0.016757
Debug: Time elapsed in L6 ANF:  0.048531
Debug: Time elapsed in L6 Pipeline:  6.352419
Debug: Time elapsed in L7:  0.397339
Debug: Printed to file in 0.439106 s..
```

and for `Time CertiCoq Compile -time -direct main_h.` I get

```
Debug: Time elapsed in Lbox:  4.398002
Debug: Time elapsed in L1g:  0.029673
Debug: Time elapsed in L2k:  0.000720
Debug: Time elapsed in L2k_eta:  0.000727
Debug: Time elapsed in L4:  0.002746
Debug: Time elapsed in L6 CPS:  0.029272
Debug: Time elapsed in L6 Pipeline:  5.565661
Debug: Time elapsed in L7:  0.679180
Debug: Printed to file in 0.473499 s..
```
which looks very reasonable I think.

**Comment by andrew-appel** [comment]
I don't understand the difference between those two "Time" commands.  Why is one of them missing Lbox?  The first one is for certicoq_benchmarks.v, what is the second one measuring?

**Comment by andrew-appel** [comment]
Why are there two Lbox lines now?

**Comment by yforster** [comment]
I updated again after I re-ran both

**Comment by zoep** [comment]
Just wanted to mention that benchmark_certicoq.v is an old version of our benchmarks, and subsumed by tests.v (which has more programs and exercises both the direct and the CPS ). The makefile (which compiles and runs all of the benchmarks) uses this file.

**Pull request merged**
